### ISSUE TITLE
Problema com o recurso de filtro na plataforma. Problema de primeira ordem

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#20]

**Comment by HerlanGeo** [comment]
Precisei fazer o filtro hoje (06/01) para o instrumento FUNDURB e o problema de perda do filtro permaneceu.

**Comment by lordscorp** [comment]
Problema deveria deixar de existir após correção do código no commit 5bb6eb7. Persistência do erro possivelmente relacionada ao cache do navegador.
Solução recomendada: limpar cache e recarregar a página (CTRL+F5).
