### ISSUE TITLE
Criar recurso para determinar se a camada terá atributos “clicáveis” ou não

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#23]

**Comment by HerlanGeo** [comment]
![Uploading image.png…]()

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103789783-27fc8180-501f-11eb-9293-ef3285278ec6.png)

**Comment by lordscorp** [comment]
O recurso foi implementado com a descrição "Ocultar informações da camada". Importante: assim como as demais opções, é preciso clicar em "Gravar dados" para salvar as alterações.

![image](https://user-images.githubusercontent.com/40305353/105047749-7bbc9100-5a49-11eb-87d1-29053405fdb6.png)

**Comment by HerlanGeo** [comment]
Olá, Renan
Essa funcionalidade ainda não aparece para gente. Já dei Crtl + F5 e continuou do mesmo jeito. Segue o print também. 
![image](https://user-images.githubusercontent.com/76186487/107994050-9dfaed80-6fba-11eb-9cf8-27aad659a6f5.png)
