### ISSUE TITLE
Possibilidade de gerar link para cada indicador na página de cadastro e configuração dos indicadores

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#26]

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103787402-4ad96680-501c-11eb-9393-6dc7e2f4632c.png)

**Comment by HerlanGeo** [comment]
Olá, Renan

Este recurso ainda não está disponível na barra de endereço para gente, caso já tenha sido possível implementá-la.
Quando escolhemos um determinado indicador para fazer as suas configurações, em Cadastro de Indicadores, a barra de endereço continua como estava, sem o id de identificação.

![image](https://user-images.githubusercontent.com/76186487/107995826-b8829600-6fbd-11eb-85aa-9ef1e02bcf64.png)
