### ISSUE TITLE
Deixar apenas ANO visível nos bancos de dados

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#30]
Ao fazer o download, todos os bancos de dados que tem coluna “Ano” (por. exemplo: 2019) incluem automaticamente mês e dia (ficando assim: 2019-01-01) o que dá uma leitura equivocada, uma vez que o dado se refere ao encerramento de 2019 (como se fosse dezembro/2019) e não ao início de 2019 (janeiro/2019). É possível deixar apenas o ano?

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103785300-cf76b580-5019-11eb-8781-c10ccb815436.png)

**Comment by Ameto11** [comment]
A fonte "Transferência do Direito de Construir (TDC): Certidão de Transferência de Potencial Construtivo" está com a data em formato `YYYY-mm-dd date`, as demais datas nas outras fontes estão em formato `YYYY/mm/dd 00:00:00.000 text`, necessário investigar o que está causando essa disparidade
