### ISSUE TITLE
Padronizar exibição de dados abertos conforme estrutura do Portal Dados Abertos da PMSP

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#31]
Falta uma barra vertical | entre Tabela e Metadados; (Será trocado pelo padrão do portal Dados Abertos da PMSP);
Metadados sempre ser a última da lista (a mais à direita); (Será trocado pelo padrão do portal Dados Abertos da PMSP);

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103784774-1fa14800-5019-11eb-9168-78f20855086c.png)

**Comment by lordscorp** [comment]
Recurso implementado suporta formato antigo até que Fonte de dados tenha sido atualizada (relacionado à issue #18 ).
Após atualização, formato de exibição é atualizado automaticamente:

![image](https://user-images.githubusercontent.com/40305353/104759978-79072680-573f-11eb-88c2-42fbe94e6b72.png)
