### ISSUE TITLE
Corrigir o nome Território “Prefeitura Regional” para “Subprefeitura” 

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#33]

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103782046-bec44080-5015-11eb-94c8-f50bab5e1a0b.png)

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/103783995-31362000-5018-11eb-93d9-c664b6248cf7.png)

**Comment by Ameto11** [comment]
Aparentemente já foi corrigido no seguinte commit de @lordscorp: 86de44f

Verifiquei a página onde esse problema ocorria e parece estar tudo certo: 
![image](https://user-images.githubusercontent.com/40498766/121055111-5aa7d300-c793-11eb-9bdd-2155da23c1d1.png)

Caso @HerlanGeo ou Rafael identifiquem esse problema novamente peço para me avisar para reabertura da issue.
