### ISSUE TITLE
Em Dados Abertos, problema com o banco de dados de EETU_IPTU_EG

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#40]
Olá, Renan. Segue o relato do problema:

Quando fazemos download do Banco de Dados de EETU_IPTU_EG, os dados da coluna de Área Terreno tem as vírgulas substituídas por pontos, e vice-versa, desconfigurando o valor real da área do terreno.

Isso acontece mesmo que tenhamos feito o upload da planilha com os dados corretos. O banco de dados que está no cadastro de fonte de dados está com os valores da referida coluna de forma correta. 

Também tentei fazer o upload novamente da planilha, mas uma mensagem de erro aparece em seguida. 

Por hora, retirei a disponibilidade deste banco dos Dados abertos, pois o usuário pode se confundir com o conteúdo da planilha. 
![WhatsApp Image 2021-02-09 at 12 48 39](https://user-images.githubusercontent.com/76186487/107404957-8a94e180-6ae5-11eb-8989-c040578fa1d0.jpeg)

Segue também o banco de dados:
[20201126_eetu_iptu eg.xlsx](https://github.com/smdu-sp/monitoramentopde/files/5953188/20201126_eetu_iptu.eg.xlsx)

**Comment by Ameto11** [comment]
@HerlanGeo Boa tarde Herlan,

Foi feita a correção da função que converte ponto para vírgula, e essa e outras fontes afetadas por esse problema agora estão funcionando corretamente.

**Comment by HerlanGeo** [comment]
Obrigado, Vinícius

Em 7 de jul de 2021, à(s) 18:34, Vinicius Giuliani ***@***.***> escreveu:

﻿

Closed #40<https://github.com/smdu-sp/monitoramentopde/issues/40> via 77720d5<https://github.com/smdu-sp/monitoramentopde/commit/77720d59824c64dee592dfa48bfa31a16d9ba502>.
