### ISSUE TITLE
Problema para atualizar o banco de dados de IPTU Progressivo

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#44]
Olá, Renan
Estou com dificuldades para atualizar o banco de dados **IPTU Progressivo no Tempo: Imóveis com cobrança**. Dá mensagem de erro no final e não consigo compreender qual é o problema apontado. 
![image](https://user-images.githubusercontent.com/76186487/108552217-c2630c80-72cf-11eb-9ea0-fe4d0c0bdeeb.png)

Indicadores associados ao banco de dados:
[Evolução da quantidade de imóveis em cobrança de IPTU Progressivo no Tempo, por ano de cobrança](https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/345)
[Evolução da quantidade de imóveis em cobrança de IPTU Progressivo no Tempo, que atenderam as condições de notificação](https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/357)

**Comment by HerlanGeo** [comment]
Segue o banco de dados:

[iptu_ano cobranca.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6012537/iptu_ano.cobranca.xlsx)

**Comment by Ameto11** [comment]
Foi identificado que o carregamento do arquivo foi feito com sucesso em 05/04, assim sendo estou fechando esta issue.
