### ISSUE TITLE
Problema para atualizar o banco de dados Operações Urbanas Consorciadas (OUC): Vinculações

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#45]
Olá, Renan.
Infelizmente também estou com dificuldades para atualizar o banco de dados supracitado, com mensagem de erro no final, e sem entender o o problema apontado. 
O indicador associado a este banco está com problema na plataforma, e também não consigo fazer nenhuma atualização nele. O indicador é [Evolução da quantidade de CEPACs vinculados](https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/98)

![image](https://user-images.githubusercontent.com/76186487/108555185-eb859c00-72d3-11eb-9f0e-925570ca7e1d.png)

Quando também tento ajustar a variável associado a este banco também aparece uma mensagem de erro:
![image](https://user-images.githubusercontent.com/76186487/108556557-f5a89a00-72d5-11eb-90fa-622df668b88a.png)

Segue o banco de dados:
[20201004_ouc_vinculacoes.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6012650/20201004_ouc_vinculacoes.xlsx)

**Comment by Ameto11** [comment]
@HerlanGeo 

Poderia confirmar se esse problema ainda está ocorrendo?

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius.

O problema não está mais acontecendo. Vou arquivar no Github
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: segunda-feira, 21 de junho de 2021 17:04
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Problema para atualizar o banco de dados Operações Urbanas Consorciadas (OUC): Vinculações (#45)


@HerlanGeo<https://github.com/HerlanGeo>

Poderia confirmar se esse problema ainda está ocorrendo?
