### ISSUE TITLE
Problemas para atualizar o banco de dados Operações Urbanas Consorciadas (OUC): Leilões

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#46]
Olá, Renan. 
Também estou com problema para atualizar os indicadores associados a este banco, além de próprio banco. Mensagens de erro no final a qual não consigo compreender de qual se trata o problema. 

![image](https://user-images.githubusercontent.com/76186487/108558392-99934500-72d8-11eb-8bf2-e729229be0c1.png)

[Evolução do estoque de CEPAC consumido](https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/99)

[20201004_ouc_leiloes.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6012797/20201004_ouc_leiloes.xlsx)

**Comment by Ameto11** [comment]
@HerlanGeo 

Poderia confirmar se esse problema ainda está ocorrendo?

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius
Este problema está resolvido. Vou finalizá-lo no Github.
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: segunda-feira, 21 de junho de 2021 17:04
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Problemas para atualizar o banco de dados Operações Urbanas Consorciadas (OUC): Leilões (#46)


@HerlanGeo<https://github.com/HerlanGeo>

Poderia confirmar se esse problema ainda está ocorrendo?
