### ISSUE TITLE
Google Analytics da plataforma parou de funcionar

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#51]
De acordo com o Rafael, não está sendo mais possível acompanhar o nível de acesso pelos usuários na plataforma, porque o Google Analytics parou de funcionar. 

![image](https://user-images.githubusercontent.com/76186487/117061739-ed6ad300-acf8-11eb-9636-56644f491b45.png)

O gráfico aparece que a Plataforma está desde Outubro sem acesso....

**Comment by Ameto11** [comment]
Foi reportado que o Analytics agora está funcionando e que foi configurado corretamente o acesso via Google Site Kit.
