### ISSUE TITLE
Dados abertos: link quebrado para download de shapefile EETU-RAIS e EETU-IPTUEG

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#56]
Em Dados Abertos, os usuários da plataforma não estão conseguindo baixar os arquivos Shapefile de EETU-RAIS e EETU-IPTU EG. Em cadastro de fonte de dados eu consigo fazer o upload corretamente, mas depois que eu faço upload eu mesmo não consigo fazer u download. 

https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/dados-abertos/

**Comment by Ameto11** [comment]
Por favor me enviar os arquivos shapefile citados para realização de testes.

**Comment by HerlanGeo** [comment]
Bom tarde, Vinícius
Encaminhei direto pelo Google Drive porque os arquivos estão pesados. Você tem acesso pelo gmail à pasta com os arquivos.

EETU RAIS: https://drive.google.com/drive/folders/1f1ZmBUpZheoil8OYn4AQqPpr2B6ZqGGP?usp=sharing
EETU-IPTU EG: https://drive.google.com/drive/folders/14NFpLFnNcS_AUlY9GnHn3HdOV91Ajjvg?usp=sharing

**Comment by HerlanGeo** [comment]
Vinícius, enviei o link dos arquivos pelo GitHub

________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: terça-feira, 29 de junho de 2021 18:03
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Author ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Dados abertos: link quebrado para download de shapefile EETU-RAIS e EETU-IPTUEG (#56)


Por favor me enviar os arquivos shapefile citados para realização de testes.

**Comment by Ameto11** [comment]
Os arquivos tem tamanho maior do que o máximo permitido para envio, que era 20 MB. 

O tamanho máximo de upload foi aumentado para 50 MB, o carregamento foi realizado novamente e o download dos arquivos está funcionando novamente.
