### ISSUE TITLE
Problema para fazer download em Dados Abertos

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#57]
Vinícius, temos recebido algumas reclamações quanto a dificuldades para fazer download de arquivos na sessão de Dados Abertos. Hoje de manhã consegui fazer o download tranquilamente, mas ontem o mesmo arquivo não podia ser baixado. Será que estamos tendo algum problema de instabilidade na plataforma?

Segue o e-mail que recebi: "Pessoal, boa tarde.

Algumas coordenadorias relataram dificuldades em obter o arquivo XLS do indicador "Fundo Municipal de Desenvolvimento Urbano (FUNDURB): Despesas", presente no site Monitoramento PDE: https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/dados-abertos/

Eu mesmo fiz o teste aqui e realmente não conseguir acessar o arquivo. Aparentemente está sem link.

O problema não é isolado e aparece para diversos outros indicadores, inclusive para outros formatos de arquivo, como CSV e TXT.

Vocês checam, por favor, o que aconteceu, e nos retornam o quanto antes, por favor?

Obrigado,

Glauco Blasco
Assessoria de Imprensa e Comunicação"

**Comment by Ameto11** [comment]
Ao realizar o carregamento da fonte de dados ontem, por algum motivo, o sistema falhou no carregamento, porém retornou que obteve sucesso. Isso causou a quebra dos arquivos e dos indicadores relacionados. 

Fiz a restauração da fonte de dados anterior, e criei o issue #58 a respeito desse problema.
