### ISSUE TITLE
BUG para visualizar valores atualizados de FUNDURB na Plataforma

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#59]
Vinícius, ontem fizemos a atualização de uns valores do banco de dados de Fundurb Despesas na plataforma. O upload foi feito e aparentemente ocorreu tudo bem. Contudo, o gráfico só mostra o valor correto quando ele está selecionado para todos os anos (2013-2020). Quando selecionamos apenas dois anos, o valor mostrado é o do banco de dados antigos. Precismos ajustar esse problema por conta dos dados que são divulgados para a imprensa.

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/127395399-919c0728-1276-4220-a67d-d21fdd7e283d.png)

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/127395510-66ef44cf-5e50-4c94-bbe5-ff494b42285c.png)

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/127395868-28bfc963-3c21-496d-8d08-0b6bfd80d2ba.png)

**Comment by Ameto11** [comment]
@HerlanGeo 

Herlan, boa noite

Fiz algumas correções, poderia confirmar se este problema foi resolvido?

**Comment by HerlanGeo** [comment]
Vinícius, deu certo sim. Muito obrigado pela ajuda!
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: quinta-feira, 29 de julho de 2021 20:30
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] BUG para visualizar valores atualizados de FUNDURB na Plataforma (#59)


@HerlanGeo<https://github.com/HerlanGeo>

Herlan, boa noite

Fiz algumas correções, poderia confirmar se este problema foi resolvido?
