### ISSUE TITLE
Implementar funcionalidade para permitir visualizar indicadores em formato 'tabela de valores'

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#6]
Implementar funcionalidade para permitir visualizar indicadores em formato 'tabela de valores'

Exemplo 1
![image](https://user-images.githubusercontent.com/40305353/102642431-6ac3eb80-413c-11eb-8664-e679662c104e.png)

Exemplo 2
![image](https://user-images.githubusercontent.com/40305353/102642462-7b746180-413c-11eb-9ebe-a0a5f7492e8f.png)

Exemplo 3
![image](https://user-images.githubusercontent.com/40305353/102642484-83340600-413c-11eb-8930-b9bc75c3c712.png)

**Comment by lordscorp** [comment]
1. Diminuir um pouco o tamanho da fonte, para ficar com mais respiro visual. Sugestão: 12px ou 10px
2. No caso de indicadores que possuem 'categoria' (legenda), esta faltando essa informação na tabela de valores. Ver o exemplo do indicador 462 (https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/462). No github, dentro dessa issue, a primeira imagem que mandamos de exemplo ilustra esses casos de indicadores (na imagem há uma coluna "Categoria" informando se o valor é pra "Não edificado", "Não utilizado" ou "Subutilizado"). 
3. Inserir barra de rolagem interna (ou outro tipo de mecanismo), pra nao ficar uma lista infinita no caso das Subprefeituras e Distritos. Ver tambem o caso do indicador 462 (https://monitoramentopde.gestaourbana.prefeitura.sp.gov.br/#/mostra_indicador/462), selecionado para Subprefeituras ou Distritos

**Comment by HerlanGeo** [comment]
Ficou muito legal esse recurso!
Só precisando fazer uns ajustes, mas já dá um up muito legal na plataforma e na forma de visualização dos dados!
