### ISSUE TITLE
Problema com indicadores de PEUC na plataforma

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#60]
Vinícius, boa tarde. 

Ontem recebemos uma demanda para atualizar o banco de dados de PEUC Imóveis notificados na plataforma. Depois de muitas tentativas e ajustes, conseguimos fazer o upload da planilha. Contudo, depois que isso foi feito os indicadores do instrumento PEUC pararam de funcionar. Hoje fiz o que foi possível para ver se eu encontrava o motivo do apagão, mas não encontrei o problema e a situação continuou a mesma. Sendo assim, pediria por gentileza para que você pudesse ver o que está acontecendo. A imprensa também está nos cobrando o funcionamento dos indicadores porque são dados que estão sendo divulgados pela mídia. 
Vou anexar a planilha que fizemos o upload.

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/127400086-d3d6b2b7-e26b-49f0-bed1-b7dba26daf32.png)

**Comment by HerlanGeo** [comment]
[Imoveis_notificados_PEUC.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6896614/Imoveis_notificados_PEUC.xlsx)

**Comment by HerlanGeo** [comment]
Vinícius, precisando falar comigo mais rápido é só me chamar no zap 11 942598785

**Comment by Ameto11** [comment]
Herlan, boa noite

Verifiquei que o problema estava na fonte de dados fornecida. Como mencionado em resposta sobre o banco do FUNDURB #8, é necessário que os nomes das colunas correspondam com as que já estão cadastradas no servidor. 

Neste caso, o problema foi que o site tinha o campo "STATUS_DE_ATENDIMENTO", e na fonte fornecida esse campo estava como "STATUS DE ATENDIMENTO". Outro problema encontrado foi que existiam duas colunas de mesmo nome, "TIPOLOGIA", e foi removida uma delas. Após essas alterações foi possível carregar a fonte de dados no site.

Outro ponto é que temos um servidor de homologação em http://monitoramentopde.comunicacao.smul.pmsp/ , recomendo fazer o upload das fontes de dados nele e, somente após verificar que não houve quebra dos indicadores relacionados, fazer o upload no site em produção, para evitar que possíveis falhas sérias como a deste caso venham a tirar do ar os indicadores da plataforma.

**Comment by HerlanGeo** [comment]
Vinícius, obrigado pela ajuda e recomendações.

Vou ter que subir novamente a planilha e vou me atentar o que você sugeriu.
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: quarta-feira, 28 de julho de 2021 21:31
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Assign ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Problema com indicadores de PEUC na plataforma (#60)


Herlan, boa noite

Verifiquei que o problema estava na fonte de dados fornecida. Como mencionado em resposta sobre o banco do FUNDURB #8<https://github.com/smdu-sp/monitoramentopde/issues/8>, é necessário que os nomes das colunas correspondam com as que já estão cadastradas no servidor.

Neste caso, o problema foi que o site tinha o campo "STATUS_DE_ATENDIMENTO", e na fonte fornecida esse campo estava como "STATUS DE ATENDIMENTO". Outro problema encontrado foi que existiam duas colunas de mesmo nome, "TIPOLOGIA", e foi removida uma delas. Após essas alterações foi possível carregar a fonte de dados no site.

Outro ponto é que temos um servidor de homologação em http://monitoramentopde.comunicacao.smul.pmsp/ , recomendo fazer o upload das fontes de dados nele e, somente após verificar que não houve quebra dos indicadores relacionados, fazer o upload no site em produção, para evitar que possíveis falhas sérias como a deste caso venham a tirar do ar os indicadores da plataforma.
