### ISSUE TITLE
Inserir texto na plataforma "Dados em parmanente revisão"

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#63]
Boa tarde, Vinícius
A equipe da plataforma do PDE está demandando que seja incluso na plataforma um aviso que informe que os dados da plataforma são revisados recorrentemente. Como algumas vezes acabamos encontrando algum problema nos dados, seria prudente que o usuário ficasse atento que as informações da plataforma podem sofrer algum tipo de revisão. 

Seria possível inserir um aviso no texto da aba "Metodologia" a seguinte mensagem:

" Para possibilitar o acompanhamento da implantação do Plano Diretor, a Prefeitura de São Paulo elaborou esta Plataforma, na qual estão definidos e são publicados com periodicidade regular, indicadores de monitoramento e avaliação.

Os indicadores de monitoramento e avaliação contemplam as diferentes dimensões de desempenho das políticas públicas presentes no Plano Diretor, abordando sua eficiência, eficácia e efetividade. Estão registrados aqui:

Os resultados em relação aos objetivos definidos no Plano Diretor, para as Macroáreas e para as Zonas Especiais.
Os avanços na realização das ações prioritárias nos Sistemas Urbanos e Ambientais.
O desempenho dos Instrumentos de Política Urbana e Gestão Ambiental.
A transparência é o ato de tornar público os dados e informações produzidos no processo de implementação do Plano Diretor, e a elaboração desta plataforma de monitoramento e avaliação são uma obrigatoriedade prevista no próprio PDE (Lei Municipal nº 16.050/14), nos arts 356 à 359. O objetivo é assegurar o conhecimento dos respectivos conteúdos à população, permitindo o controle e a fiscalização.

Baseado na avaliação de indicadores, esta plataforma pretende fomentar pesquisas e processos de revisão, aperfeiçoamento e elaboração de planos, programas e projetos setoriais, regionais e locais de políticas públicas. Foram organizados procedimentos de registro e tabulação de dados das políticas públicas já regulamentadas pela Prefeitura de São Paulo, com objetivo de gerar bancos de dados padronizados, procedimentos para sua atualização e melhorias na gestão da informação.

Foi também instituído o Comitê Intersecretarial de Monitoramento e Avaliação da Implementação do Plano Diretor Estratégico (CIMPDE), com atribuições e composição definidas pelo Decreto nº 57.490/16. Fazem parte do CIMPDE representantes de diferentes áreas da Prefeitura relacionadas com as dinâmicas espaciais definidas no PDE e membros do Conselho Municipal de Desenvolvimento Urbano (CMPU), instância de participação popular, composta por integrantes do Poder Público e da Sociedade Civil. O objetivo é garantir que o monitoramento e avaliação do Plano Diretor seja fruto de um processo de aperfeiçoamento contínuo, coletivo, interdisciplinar, participativo e democrático.

* Observamos que os dados e informações disponibilizados na plataforma são atualizados anualmente, tão como periodicamente revisados e aprimorados."

**Comment by Ameto11** [comment]
Boa tarde, Herlan

Foi adicionado o aviso à página solicitada.
