### ISSUE TITLE
Alterar texto de atualização do indicador

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#64]
Alterar nos indicadores o texto de "Atualizado em: Dezembro 2019" para "Atualizado até: Dezembro 2019"

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/132748713-82631083-ed4c-4618-860a-245c5ff22e17.png)

**Comment by Ameto11** [comment]
Boa tarde Herlan,

O texto do indicador foi alterado, conforme solicitado.
