### ISSUE TITLE
Atualizar o texto da Metodologia da Plataforma

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#67]
Olá, Vinícius
Precisamos atualizar um trecho do texto que descreve a metodologia da plataforma. Substituir pelo conteúdo que está em negrito.

"Os indicadores de monitoramento e avaliação contemplam as diferentes dimensões de desempenho das políticas públicas presentes no Plano Diretor, abordando sua eficiência, eficácia e efetividade. **A Plataforma de Monitoramento do PDE tem como objetivos acompanhar**:

- os resultados em relação aos objetivos definidos no Plano Diretor, para as Macroáreas e para as Zonas Especiais.
- os avanços na realização das ações prioritárias nos Sistemas Urbanos e Ambientais.
- o desempenho dos Instrumentos de Política Urbana e Gestão Ambiental.

**Comment by vgiuliani11** [comment]
Atualização realizada.

**Comment by HerlanGeo** [comment]
> Atualização realizada.

Obrigado, Vinícius
