### ISSUE TITLE
Trocar cor de botão de formatado de arquivo a ser baixado na página de Dados Abertos

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#71]
@vgiuliani11 Seria possível trocar a cor de cinza do botão dos formatos de arquivos para download para outras cores?
Digo isso porque a cor cinza dá a impressão que o arquivo para download não está disponível. 

Sugestão de cores:
Shapefile - roxo
KMZ - azul
TXT - laranja

Trocar a cor de Tabela de verde para azul claro.

**Comment by HerlanGeo** [comment]
Vinícius, ficou ótimo!

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vgiuliani11** [comment]
A alteração foi realizada e está no ar
