### ISSUE TITLE
Problema para carregar arquivo xls de metadados na plataforma

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#77]
Boa tarde, Vinícius
Quando tentamos carregar o arquivo xls dos metadados na plataforma, ele demora a carregar e acaba não indo. 

Você poderia checar por gentileza o que está acontecendo?
![image](https://user-images.githubusercontent.com/76186487/163249933-ea011bf3-3f25-4fcd-80b9-565cb628a211.png)

**Comment by HerlanGeo** [comment]
[msp_sisacoe_metadados.xlsx](https://github.com/smdu-sp/monitoramentopde/files/8483933/msp_sisacoe_metadados.xlsx)

Estou anexando o Metadados da fonte Município de SP - Sisacoe, caso queira utilizar como teste.

**Comment by vgiuliani11** [comment]
@HerlanGeo 

Olá Herlan, boa tarde

Consegui identificar o que estava causando o problema, poderia verificar se o envio de metadados está funcionando novamente?
