### ISSUE TITLE
Problema para carregar Banco de Dados Sisacoe 2021 EETU

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#78]
Boa tarde, Vinícius
Estou tendo dificuldades para carregar o BD SISACOE_EETU_2021 na plataforma do PDE. Fui fazendo inúmeras correções na planilha, conforme as mensagens de erro iam aparecendo. Mas essa última mensagem eu não consigo interpretar sobre o que se trata, e esgotei as minhas habilidades para tentar resolver por aqui. 
Não sei se tem a ver com o fato de que em algumas colunas com dados numéricos tenham campos com preenchimento não numérico, mas observo que conseguíamos subir essas colunas assim em outras atualizações sem problema.

Pediria a gentileza de você tentar subi-la na plataforma para identificar qual seria o problema na seguinte cadastro de fonte: Eixos de Estruturação da Transformação Urbana (EETU): Empreendimentos licenciados (SISACOE)

Segue o BD em anexo.

![image](https://user-images.githubusercontent.com/76186487/163846612-ea27152f-ec60-407c-b800-125a61209296.png)

![image](https://user-images.githubusercontent.com/76186487/163846137-edd21df5-3442-4f53-8e7a-f9c448769794.png)

**Comment by HerlanGeo** [comment]
BD em anexo:

[eetu_empreendimentos_sisacoe_2021.xlsx](https://github.com/smdu-sp/monitoramentopde/files/8507099/eetu_empreendimentos_sisacoe_2021.xlsx)

**Comment by vgiuliani11** [comment]
Olá Herlan, boa tarde

Identifiquei que o problema é causado por que a estrutura da tabela que está tentando inserir difere da esperada pelo sistema.

A variável "Quantidade de unidades habitacionais HMP nos empreendimentos licenciados nos EETU", que depende da fonte em questão, possui os seguintes parâmetros:

![image](https://user-images.githubusercontent.com/40498766/163875213-2ba1858c-95ea-45a3-a740-e3c4f5071280.png)

Verifiquei que na tabela nova os seguintes valores foram alterados:

- (Coluna) 'unidades_habitacionais' -> 'unidades_residenciais'
- 'Não se aplica' -> 'Nao se aplica'
- 'Informação não presente no alvará' -> 'Informacao nao presente no alvara'

Após reverter as alterações, consegui realizar o envio da fonte de dados **no site de homologação**.

Segue arquivo com as alterações, por favor verificar se consegue realizar o carregamento no site em produção.

[eetu_empreendimentos_sisacoe_2021-corrigido.xlsx](https://github.com/smdu-sp/monitoramentopde/files/8508122/eetu_empreendimentos_sisacoe_2021-corrigido.xlsx)
