### ISSUE TITLE
Mapa Subprefeituras não aparece no cartograma Plataforma

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#79]
Olá, Vinícius
Você poderia por gentileza checar o porquê do mapa das subprefeitura não estar carregando no cartograma dos indicadores?
Está aparecendo uma mensagem de erro e isso está acontecendo com todos os indicadores.

![image](https://user-images.githubusercontent.com/76186487/169135827-831de0a3-2c2c-416e-84b4-1029ff614c43.png)

**Comment by vgiuliani11** [comment]
Olá Herlan, boa tarde

Acho que encontrei o problema, poderia verificar se agora está funcionando corretamente?
