### ISSUE TITLE
Fundurb despesas - não carrega dados de 2019

### ISSUE THREAD

**Issue by lordscorp** [smdu-sp/monitoramentopde#8]
Supraterritorial / não identificada - criar 2 unidades territoriais de análise: "Supraterritorial" / "Supradistrital"

**Comment by lordscorp** [comment]
Possível falha na carga da fonte de dados.
Necessário realizar nova carga.

**Comment by lordscorp** [comment]
Necessário informar mais dados para a criação das 2 unidades territoriais de análise: hierarquia, território pai e ordem.

**Comment by HerlanGeo** [comment]
Alguns indicadores não aparecem os dados de 2019
![image](https://user-images.githubusercontent.com/76186487/103797106-ca6c3300-5026-11eb-8eea-e6470a2938ab.png)

**Comment by HerlanGeo** [comment]
Em alguns aparece o ano de 2019
![image](https://user-images.githubusercontent.com/76186487/103797267-00a9b280-5027-11eb-91e2-2a6b6390e2b8.png)

**Comment by HerlanGeo** [comment]
Olá, Renan
Sobre esta issue de Fundurb, falta alguma coisa da nossa parte para fazer?
Continuo tendo dificuldades para atualizar os indicadores deste instrumento. 
Não consigo dar carga no banco de dados atualizado, tanto em Receitas quando em Despesas, e nem fazer qualquer tipo de ajuste nos indicadores. 
![image](https://user-images.githubusercontent.com/76186487/107670827-e8563480-6c71-11eb-85ff-b2f43c4b2fc1.png)

**Comment by Ameto11** [comment]
> Alguns indicadores não aparecem os dados de 2019
> ![image](https://user-images.githubusercontent.com/76186487/103797106-ca6c3300-5026-11eb-8eea-e6470a2938ab.png)

@HerlanGeo,

Poderia verificar se ainda ocorre erro ao tentar carregar fonte de dados atual do indicador "FUNDURB: Despesas", e caso positivo, me enviar o arquivo que está tentando carregar?

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius

Continuamos a ter problemas com esses bancos de dados.

Segue em anexo o banco de dados.
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: segunda-feira, 21 de junho de 2021 16:58
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Fundurb despesas - não carrega dados de 2019 (#8)


Alguns indicadores não aparecem os dados de 2019
[image]<https://user-images.githubusercontent.com/76186487/103797106-ca6c3300-5026-11eb-8eea-e6470a2938ab.png>

@HerlanGeo<https://github.com/HerlanGeo>,

Poderia verificar se ainda ocorre erro ao tentar carregar fonte de dados atual do indicador "FUNDURB: Despesas", e caso positivo, me enviar o arquivo que está tentando carregar?

**Comment by Ameto11** [comment]
@HerlanGeo 

Boa tarde Herlan,

Não recebi o arquivo, poderia enviar por link, ou anexar via comentário diretamente no Github

**Comment by HerlanGeo** [comment]
> @HerlanGeo
> 
> Boa tarde Herlan,
> 
> Não recebi o arquivo, poderia enviar por link, ou anexar via comentário diretamente no Github

Segue o arquivo, Vinícius
[20190916_fundurb_despesas.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6742788/20190916_fundurb_despesas.xlsx)

**Comment by HerlanGeo** [comment]
Vinícius, foi enviado pelo github.
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: terça-feira, 29 de junho de 2021 17:43
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Fundurb despesas - não carrega dados de 2019 (#8)


@HerlanGeo<https://github.com/HerlanGeo>

Boa tarde Herlan,

Não recebi o arquivo, poderia enviar por link, ou anexar via comentário diretamente no Github

**Comment by Ameto11** [comment]
> > @HerlanGeo
> > Boa tarde Herlan,
> > Não recebi o arquivo, poderia enviar por link, ou anexar via comentário diretamente no Github
> 
> Segue o arquivo, Vinícius
> [20190916_fundurb_despesas.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6742788/20190916_fundurb_despesas.xlsx)

@HerlanGeo 

Herlan, boa tarde.

Verifiquei o arquivo enviado e os dados contidos nele vão apenas até a data de 2018. Está certo que esse é o arquivo mais recente?

Foi apontado que certos indicadores possuem dados de 2019, ao verificar notei que eles não usam fonte de dados FUNDURB - Despesas, mas, sim, FUNDURB - Receitas que, de fato, possui dados pós-2018.

**Comment by HerlanGeo** [comment]
> > > @HerlanGeo
> > > Boa tarde Herlan,
> > > Não recebi o arquivo, poderia enviar por link, ou anexar via comentário diretamente no Github
> > 
> > 
> > Segue o arquivo, Vinícius
> > [20190916_fundurb_despesas.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6742788/20190916_fundurb_despesas.xlsx)
> 
> @HerlanGeo
> 
> Herlan, boa tarde.
> 
> Verifiquei o arquivo enviado e os dados contidos nele vão apenas até a data de 2018. Está certo que esse é o arquivo mais recente?
> 
> Foi apontado que certos indicadores possuem dados de 2019, ao verificar notei que eles não usam fonte de dados FUNDURB - Despesas, mas, sim, FUNDURB - Receitas que, de fato, possui dados pós-2018.

Boa tarde, Vinícius

Bem observado. Não é essa a planilha com os dados de 2019. Segue o arquivo correto.
[fundurb_despesas.xlsx](https://github.com/smdu-sp/monitoramentopde/files/6743598/fundurb_despesas.xlsx)

**Comment by HerlanGeo** [comment]
Boa tarde, @Ameto11. (Vinícius)

Sobre os problemas com os bancos de dados de Fundurb, houve algum avanço para a solução dessa issue?

O Secretário da SMUL está nos cobrando essa atualização dos dados, porque é uma informação importante para a revisão do Plano Diretor. 

Por favor, nos dê um parecer de como anda a solução desse problema. Se a questão ainda estiver complexa de resolver, talvez seja o caso de vermos com o Renan o que pode ser feito para resolver o problema de forma mais rápida. 

Obrigado e até!

**Comment by Ameto11** [comment]
@HerlanGeo Boa tarde Herlan

Ainda estou investigando esse problema. Houve uma mudança considerável na estruturação dos dados dessa fonte em comparação com a anterior, estou tentando determinar se o problema é com a fonte de dados, com a plataforma, ou ambos. 

Estou realizando testes no servidor de homologação, assim que tiver os dados necessários eu retorno com mais informações.

**Comment by HerlanGeo** [comment]
Olá, Vinícius.

Obrigado pelo retorno.

Vai me atualizando e se precisar de alguma ajuda me fale.

Nessa semana agora a Coordenadora da Planurb quer fazer uma reunião sobre a plataforma de monitoramento. Vamos ver um horário possível para todos. Vamos nos falando. Abraço e bom fim de semana.
________________________________
De: Vinicius Giuliani ***@***.***>
Enviado: sexta-feira, 2 de julho de 2021 15:24
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Fundurb despesas - não carrega dados de 2019 (#8)


@HerlanGeo<https://github.com/HerlanGeo> Boa tarde Herlan

Ainda estou investigando esse problema. Houve uma mudança considerável na estruturação dos dados dessa fonte em comparação com a anterior, estou tentando determinar se o problema é com a fonte de dados, com a plataforma, ou ambos.

Estou realizando testes no servidor de homologação, assim que tiver os dados necessários eu retorno com mais informações.

**Comment by Ameto11** [comment]
@HerlanGeo Boa noite

Foi realizado com sucesso o carregamento da fonte de dados à plataforma e os indicadores estão exibindo os dados de 2019. Para tal, foram corrigidos os seguintes problemas com a fonte de dados "fundurb_despesas.xlsx" fornecida:

1. Um dos motivos que estava impedindo o upload da fonte de dados é que no arquivo fornecido houve mudança estrutural da fonte de dados, com a alteração dos nomes das colunas. O sistema não tem acomodações para tais mudanças, e o site quebraria caso o upload fosse permitido, pois as variáveis e indicadores estariam configurados para acessar as colunas que não existem mais no banco de dados.

Dessa forma, as seguintes colunas foram renomeadas de forma a se adequar ao formato usado anteriormente:

- ID_NOVO -> ID
- SECRETARIA_RESP -> SECRTARIA_RESP
- COD_DIST -> COD_DISTRITO
- COD_SUB -> COD_SUBPREFEITURA
- COD_MACRO -> COD_MACROAREA
- MACROAREA -> MACRO

2. No arquivo fornecido foi atribuído o código "0" aos distritos, subprefeituras e macroáreas de valor "NÃO SE APLICA". Isso estava causando conflito, pois ao fazer o carregamento o sistema realizava consulta e não encontrava nenhuma correspondência de unidade territorial de código 0. 

Para corrigir esse aspecto, foi removido esse valor e as células foram deixadas em branco, como estava sendo feito anteriormente.

3. Os itens 2014.20.002 e 2015.22.010 possuíam ambos na coluna "ENDERECO" o caractere de quebra de linha, o que causava problemas na inserção no banco de dados. 

Esse caractere foi substituído por ";" de forma a seguir o padrão dos dados já contidos nessas células.
