### ISSUE TITLE
Planilha Objetivos do PDE - Associação de indicadores

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#82]
Boa tarde, Vinícius

Gostaria que fosse feito o upload de uma planilha contendo os Objetivos do PDE na plataforma, para que pudéssemos associar os indicadores existentes a esses objetivos. 

Atualmente, em cadastrao de indicadores, no campo dos Objetivos a lista suspensa com eles não está disponível. 

É necessário que o indicador possa ser associado a mais de um Objetivo. Estou anexando a planilha com o número dos Objetivos e a descrição deles. Também estou enviando umas figuras simulando como deverá ficar na plataforma. 

---
### Cadastro de objetivos

- [x] Cadastrar os objetivos com as descrições
- [x] Ordenar os objetivos na caixa de seleção

### Cadastro de indicadores

- [x] Ordenar os objetivos na caixa de seleção
- [x] Associar indicador a mais de um objetivo
- [x] Remover um objetivo após adicionado

### Monitoramento

- [x] Carregar a lista de objetivos e popular o caixa de seleção
- [x] Quando objetivo é selecionado, mostrar nome e descrição ao invés da interface de instrumentos com mapa temático
- [x] Filtrar indicadores corretamente ao selecionar objetivo

### API

- [x] Retornar objetivos associados a certos indicadores
- [x] Configurar endpoint para retornar grupos de indicadores do tipo `objetivo`
- [x] Alterar os endpoints de indicador para resgatar e salvar mais de um objetivo

**Comment by HerlanGeo** [comment]
A planilha contendo os Objetivos
[Objetivos PDE Vinícius.xlsx](https://github.com/smdu-sp/monitoramentopde/files/8902203/Objetivos.PDE.Vinicius.xlsx)

**Comment by HerlanGeo** [comment]
![image](https://user-images.githubusercontent.com/76186487/173650074-3de3faf4-b224-44e9-b1e3-fa53dcc30bf1.png)


![teste_200629-001](https://user-images.githubusercontent.com/76186487/173649033-0decb102-6960-4ffb-bdfe-bfc63bbca52a.png)
![teste_200629-002](https://user-images.githubusercontent.com/76186487/173649126-cece0c11-16ec-4576-8d55-f51f66cb4a14.png)

**Comment by vgiuliani11** [comment]
Olá, Herlan,

Os objetivos foram inseridos na plataforma, porém é necessário desenvolvimento para implementar a associação de indicador a mais de um objetivo, e também para a exibição dos indicadores associados com os objetivos na página principal. 

Por enquanto recomendo não adicionar os objetivos aos indicadores, e assim que as questões acima estiverem resolvidas avisarei para que possa retomar essa questão.

Uma dúvida, quando selecionado um objetivo, o que deve ser exibido no campo que aparece logo abaixo das caixas de seleção, apenas o título do objetivo e a descrição, e nada mais?

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius.


Uma dúvida, quando selecionado um objetivo, o que deve ser exibido no campo que aparece logo abaixo das caixas de seleção, apenas o título do objetivo e a descrição, e nada mais?

—

Vinícius, se você estiver falando da interface para o usuário, é apenas o título e a descrição mesmo. Logo após deverão aparecer os inicadores associados ao Objetivo. Neste caso não haverá mapa, como nos Objetivos das Zonas Especiais.

No cadastro de Indicadores poderia ser como o sugerido por vc também. Assim que fosse selecionado o número do Objetivo, abaixo apareceria a descrição.

Veja se ficou compreensível, e qualquer coisa me chama.
________________________________
De: vgiuliani11 ***@***.***>
Enviado: quarta-feira, 15 de junho de 2022 20:04
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Manual ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Planilha Objetivos do PDE - Associação de indicadores (Issue #82)


Olá, Herlan,

Os objetivos foram inseridos na plataforma, porém é necessário desenvolvimento para implementar a associação de indicador a mais de um objetivo, e também para a exibição dos indicadores associados com os objetivos na página principal.

Por enquanto recomendo não adicionar os objetivos aos indicadores, e assim que as questões acima estiverem resolvidas avisarei para que possa retomar essa questão.

Uma dúvida, quando selecionado um objetivo, o que deve ser exibido no campo que aparece logo abaixo das caixas de seleção, apenas o título do objetivo e a descrição, e nada mais?

**Comment by vgiuliani11** [comment]
@HerlanGeo 

Olá Herlan,

Foi adicionado à página de cadastro de indicadores a opção para adicionar objetivos ao indicador:

![image](https://user-images.githubusercontent.com/40498766/176558435-b32fb05d-753e-4b0b-a8fb-5c5e43792cf0.png)

Por favor verificar se está funcionando adequadamente.

Também já foi colocado no ar a visualização de indicadores por objetivo, assim que associados os indicadores deverão aparecer na listagem.

![image](https://user-images.githubusercontent.com/40498766/176559288-a9828279-c73c-47b0-88c7-b2709f44c4d2.png)

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius

Obrigado. Eu vou avaliar e te dar um retorno.
________________________________
De: vgiuliani11 ***@***.***>
Enviado: quarta-feira, 29 de junho de 2022 19:57
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Mention ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Planilha Objetivos do PDE - Associação de indicadores (Issue #82)


@HerlanGeo<https://github.com/HerlanGeo>

Olá Herlan,

Foi adicionado à página de cadastro de indicadores a opção para adicionar objetivos ao indicador:

[image]<https://user-images.githubusercontent.com/40498766/176558435-b32fb05d-753e-4b0b-a8fb-5c5e43792cf0.png>

Por favor verificar se está funcionando adequadamente.

Também já foi colocado no ar a visualização de indicadores por objetivo, assim que associados os indicadores deverão aparecer na listagem.

[image]<https://user-images.githubusercontent.com/40498766/176559288-a9828279-c73c-47b0-88c7-b2709f44c4d2.png>

**Comment by HerlanGeo** [comment]
Vinícius, boa tarde. Sobre a avaliação do recurso dos Objetivos na Plataforma, fiz alguns testes aqui. 
Como administrador eu estou conseguindo associar os indicadores com os Objetivos. Contudo, na plataforma para o usuário comum essa associação não está aparecendo. Pode verificar o que está acontecendo?
![image](https://user-images.githubusercontent.com/76186487/176956143-3e208ee4-d5cd-46e0-b3ae-9e90ad9a7548.png)
![image](https://user-images.githubusercontent.com/76186487/176956629-111f2d7b-90b3-43ba-a904-3066a16804a5.png)

**Comment by HerlanGeo** [comment]
Vinícius, fiz alguns testes aqui e aparentemente a associação dos indicadores está funcionando.

**Comment by vgiuliani11** [comment]
Herlan, boa tarde!

Muito obrigado pelo retorno. 

Vou marcar este problema como resolvido, caso surja alguma questão relacionada aos Objetivos, por favor reabrir o problema para adicionar informações.
