### ISSUE TITLE
Possibilidade de regular o tamanho da feição de ponto dos mapas temáticos

### ISSUE THREAD

**Issue by HerlanGeo** [smdu-sp/monitoramentopde#84]
Bom dia, Vinícius

Gostaríamos que você avaliasse se é possível criar um recurso na página de configuração dos mapas temáticos na plataforma para regular o tamanho das feições do ponto da camada KML. 

Atualmente não temos essa possibilidade, e isso dificulta tematizarmos o mapa de maneira mais adequada para visualização dos dados georreferenciados.

**Comment by HerlanGeo** [comment]
![WhatsApp Image 2022-09-12 at 11 52 11](https://user-images.githubusercontent.com/76186487/189691375-a5b313d3-41fc-483b-abc4-75f0603e38f6.jpeg)

**Comment by vgiuliani11** [comment]
Herlan, bom dia,

Adicionei a propriedade "Tamanho do ponto" ao editor do estilo da camada, poderia verificar se isso atende a solicitação?

**Comment by HerlanGeo** [comment]
Boa tarde, Vinícius

Está funcionando adequadamente! Muito obrigado!
________________________________
De: vgiuliani11 ***@***.***>
Enviado: terça-feira, 13 de setembro de 2022 12:51
Para: smdu-sp/monitoramentopde ***@***.***>
Cc: HERLAN ALCANTARA ***@***.***>; Assign ***@***.***>
Assunto: Re: [smdu-sp/monitoramentopde] Possibilidade de regular o tamanho da feição de ponto dos mapas temáticos (Issue #84)


Herlan, bom dia,

Adicionei a propriedade "Tamanho do ponto" ao editor do estilo da camada, poderia verificar se isso atende a solicitação?
